"""Initial migration: messages table (Phase 5's MessageRecord).

Revision ID: a447c3190db3
Revises:
Create Date: Phase 10

Hand-written rather than autogenerated: this project's dev/CI
environments don't always have a live Postgres to compare against, and
the schema is simple enough (one table, four columns, one index) that
writing it directly is both faster and less error-prone than debugging
an autogenerate run against the wrong dialect. If you add models later
and have a real Postgres available, `alembic revision --autogenerate`
is the right tool from that point on — this migration just establishes
the starting point.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a447c3190db3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_messages_conversation_id_created_at",
        "messages",
        ["conversation_id", "created_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_messages_conversation_id_created_at", table_name="messages")
    op.drop_table("messages")
